image:
  name: cr.d.xiaomi.net/doris/doris:1.3-mdh-1.0

variables:
  KUBERNETES_CPU_REQUEST: 6
  KUBERNETES_MEMORY_REQUEST: 16Gi

before_script:
  - ulimit -a
  - echo "Working Directory is $(pwd)"
  - ln -sf /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime  
  - date -R  

stages:
  - test
  - build
  - package

test_be_job:
  stage: test
  script:
    - ./run-be-ut.sh --run

test_be_job_asan:
  stage: test
  script:
    - BUILD_TYPE=ASAN ./run-be-ut.sh --run

test_be_job_lsan:
  stage: test
  script:
    - BUILD_TYPE=LSAN ./run-be-ut.sh --run

test_fe_job:
  stage: test
  script:
    - ./run-fe-ut.sh

package_job:
  only:
    - tags
    - branch-0.13-mdh
  stage: package
  variables:
    MINOS_CONFIG_FILE: '/root/deployment-config/deploy.cfg'
    MINOS2_CONFIG_FILE: '/root/deployment/deploy.cfg'
  script:
    - cd /root/minos && git pull
    - cd ../ && cd deployment-config && git pull
    - cd ../ && cd deployment && git pull
    - cd $CI_PROJECT_DIR && ./make_distribution.sh
    - BUILD_VERSION=`egrep "^build_version" $CI_PROJECT_DIR/gensrc/script/gen_build_version.sh | awk '-F"' '{print $2}'`
    - cd /root/minos/client/ && ./package install doris --package_dir=$CI_PROJECT_DIR --version=$BUILD_VERSION
  when: on_success
